import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { Product } from './models/Product';
import { Retailer } from './models/Retailer';

dotenv.config();

const seedProducts = [
  // BAGS
  {
    name: 'GG Marmont Small Shoulder Bag',
    brand: 'Gucci',
    category: 'Bags',
    description: 'The small GG Marmont chain shoulder bag has a softly structured shape and an oversized flap closure with Double G hardware.',
    originalPrice: 2350,
    ourPrice: 1699,
    discount: 28,
    images: ['https://picsum.photos/seed/gucci-bag-1/800/1000'],
    sizes: ['One Size'],
    retailerSource: 'Saks',
    retailerUrl: 'https://saks.com/gucci-gg-marmont',
    inStock: true,
    sku: 'GUCCI-BAG-001',
  },
  {
    name: 'Re-Edition 2005 Saffiano Leather Bag',
    brand: 'Prada',
    category: 'Bags',
    description: 'This iconic Prada bag is reissued in soft nappa leather with the signature triangle logo.',
    originalPrice: 1850,
    ourPrice: 1299,
    discount: 30,
    images: ['https://picsum.photos/seed/prada-bag-1/800/1000'],
    sizes: ['One Size'],
    retailerSource: 'Nordstrom',
    retailerUrl: 'https://nordstrom.com/prada-reedition',
    inStock: true,
    sku: 'PRADA-BAG-001',
  },
  {
    name: 'Loulou Small Bag in Quilted Leather',
    brand: 'Saint Laurent',
    category: 'Bags',
    description: 'The Loulou Small features iconic YSL monogram hardware on quilted leather.',
    originalPrice: 2590,
    ourPrice: 1899,
    discount: 27,
    images: ['https://picsum.photos/seed/ysl-bag-1/800/1000'],
    sizes: ['One Size'],
    retailerSource: 'Neiman Marcus',
    retailerUrl: 'https://neimanmarcus.com/ysl-loulou',
    inStock: true,
    sku: 'YSL-BAG-001',
  },
  {
    name: 'Le Cagole XS Shoulder Bag',
    brand: 'Balenciaga',
    category: 'Bags',
    description: 'Le Cagole features adjustable straps and signature hardware in aged buffalo leather.',
    originalPrice: 1890,
    ourPrice: 1299,
    discount: 31,
    images: ['https://picsum.photos/seed/balenciaga-bag-1/800/1000'],
    sizes: ['One Size'],
    retailerSource: 'Saks',
    retailerUrl: 'https://saks.com/balenciaga-cagole',
    inStock: true,
    sku: 'BALENCIAGA-BAG-001',
  },
  {
    name: 'Cassette Bag in Intrecciato',
    brand: 'Bottega Veneta',
    category: 'Bags',
    description: 'Woven nappa leather cassette bag with magnetic closure.',
    originalPrice: 3200,
    ourPrice: 2400,
    discount: 25,
    images: ['https://picsum.photos/seed/bv-bag-1/800/1000'],
    sizes: ['One Size'],
    retailerSource: 'Nordstrom',
    retailerUrl: 'https://nordstrom.com/bv-cassette',
    inStock: true,
    sku: 'BV-BAG-001',
  },
  {
    name: 'Pouch in Folded Leather',
    brand: 'Loewe',
    category: 'Bags',
    description: 'Soft anagram leather pouch with magnetic closure.',
    originalPrice: 1590,
    ourPrice: 1099,
    discount: 31,
    images: ['https://picsum.photos/seed/loewe-bag-1/800/1000'],
    sizes: ['One Size'],
    retailerSource: 'Neiman Marcus',
    retailerUrl: 'https://neimanmarcus.com/loewe-pouch',
    inStock: true,
    sku: 'LOEWE-BAG-001',
  },
  {
    name: 'Triomphe Bag in Shiny Calfskin',
    brand: 'Celine',
    category: 'Bags',
    description: 'Signature Triomphe closure on smooth calfskin leather.',
    originalPrice: 2900,
    ourPrice: 2100,
    discount: 28,
    images: ['https://picsum.photos/seed/celine-bag-1/800/1000'],
    sizes: ['One Size'],
    retailerSource: 'Saks',
    retailerUrl: 'https://saks.com/celine-triomphe',
    inStock: true,
    sku: 'CELINE-BAG-001',
  },
  {
    name: 'Classic Flap Bag Medium',
    brand: 'Chanel',
    category: 'Bags',
    description: 'The iconic Chanel flap bag in quilted lambskin with CC turn-lock.',
    originalPrice: 8200,
    ourPrice: 5999,
    discount: 27,
    images: ['https://picsum.photos/seed/chanel-bag-1/800/1000'],
    sizes: ['Medium'],
    retailerSource: 'Neiman Marcus',
    retailerUrl: 'https://neimanmarcus.com/chanel-flap',
    inStock: true,
    sku: 'CHANEL-BAG-001',
  },
  {
    name: 'Speedy 30 Bandouliere',
    brand: 'Louis Vuitton',
    category: 'Bags',
    description: 'The iconic Speedy bag in Monogram canvas with removable strap.',
    originalPrice: 1590,
    ourPrice: 1150,
    discount: 28,
    images: ['https://picsum.photos/seed/lv-bag-1/800/1000'],
    sizes: ['30'],
    retailerSource: 'Nordstrom',
    retailerUrl: 'https://nordstrom.com/lv-speedy',
    inStock: true,
    sku: 'LV-BAG-001',
  },
  {
    name: 'Arco Bag in Leather',
    brand: 'Loewe',
    category: 'Bags',
    description: 'Contemporary tote in supple calfskin with signature anagram.',
    originalPrice: 2850,
    ourPrice: 1999,
    discount: 30,
    images: ['https://picsum.photos/seed/loewe-bag-2/800/1000'],
    sizes: ['One Size'],
    retailerSource: 'Saks',
    retailerUrl: 'https://saks.com/loewe-arco',
    inStock: true,
    sku: 'LOEWE-BAG-002',
  },
  // SHOES
  {
    name: 'Suede Ankle Boots',
    brand: 'Gucci',
    category: 'Shoes',
    description: 'Iconic horsebit suede ankle boots with block heel.',
    originalPrice: 1200,
    ourPrice: 799,
    discount: 33,
    images: ['https://picsum.photos/seed/gucci-shoe-1/800/1000'],
    sizes: ['36', '37', '38', '39', '40', '41'],
    retailerSource: 'Saks',
    retailerUrl: 'https://saks.com/gucci-boots',
    inStock: true,
    sku: 'GUCCI-SHOE-001',
  },
  {
    name: 'Monolith Patent Leather Loafers',
    brand: 'Prada',
    category: 'Shoes',
    description: 'Iconic chunky sole loafers in patent leather.',
    originalPrice: 1450,
    ourPrice: 995,
    discount: 31,
    images: ['https://picsum.photos/seed/prada-shoe-1/800/1000'],
    sizes: ['39', '40', '41', '42', '43'],
    retailerSource: 'Nordstrom',
    retailerUrl: 'https://nordstrom.com/prada-loafers',
    inStock: true,
    sku: 'PRADA-SHOE-001',
  },
  {
    name: 'Wyatt Harness Boots',
    brand: 'Saint Laurent',
    category: 'Shoes',
    description: 'Classic Western-inspired harness boots in leather.',
    originalPrice: 1495,
    ourPrice: 1049,
    discount: 30,
    images: ['https://picsum.photos/seed/ysl-shoe-1/800/1000'],
    sizes: ['40', '41', '42', '43'],
    retailerSource: 'Neiman Marcus',
    retailerUrl: 'https://neimanmarcus.com/ysl-wyatt',
    inStock: true,
    sku: 'YSL-SHOE-001',
  },
  {
    name: 'Track Sneakers',
    brand: 'Balenciaga',
    category: 'Shoes',
    description: 'Chunky track sneakers in mixed materials.',
    originalPrice: 895,
    ourPrice: 649,
    discount: 27,
    images: ['https://picsum.photos/seed/balenciaga-shoe-1/800/1000'],
    sizes: ['39', '40', '41', '42', '43', '44'],
    retailerSource: 'Saks',
    retailerUrl: 'https://saks.com/balenciaga-track',
    inStock: true,
    sku: 'BALENCIAGA-SHOE-001',
  },
  {
    name: 'Puddle Boots',
    brand: 'Bottega Veneta',
    category: 'Shoes',
    description: 'Rubber puddle boots with signature intrecciato pattern.',
    originalPrice: 750,
    ourPrice: 499,
    discount: 33,
    images: ['https://picsum.photos/seed/bv-shoe-1/800/1000'],
    sizes: ['36', '37', '38', '39', '40', '41'],
    retailerSource: 'Nordstrom',
    retailerUrl: 'https://nordstrom.com/bv-puddle',
    inStock: true,
    sku: 'BV-SHOE-001',
  },
  {
    name: 'Penny Loafers',
    brand: 'Gucci',
    category: 'Shoes',
    description: 'Classic penny loafers with Web detail.',
    originalPrice: 890,
    ourPrice: 599,
    discount: 33,
    images: ['https://picsum.photos/seed/gucci-shoe-2/800/1000'],
    sizes: ['39', '40', '41', '42', '43'],
    retailerSource: 'Neiman Marcus',
    retailerUrl: 'https://neimanmarcus.com/gucci-loafers',
    inStock: true,
    sku: 'GUCCI-SHOE-002',
  },
  // CLOTHING
  {
    name: 'Silk Crepe Blouse',
    brand: 'Gucci',
    category: 'Clothing',
    description: 'Flowing silk blouse with signature GG buttons.',
    originalPrice: 1500,
    ourPrice: 999,
    discount: 33,
    images: ['https://picsum.photos/seed/gucci-cloth-1/800/1000'],
    sizes: ['XS', 'S', 'M', 'L'],
    retailerSource: 'Saks',
    retailerUrl: 'https://saks.com/gucci-blouse',
    inStock: true,
    sku: 'GUCCI-CLOTH-001',
  },
  {
    name: 'Re-Nylon Puffer Jacket',
    brand: 'Prada',
    category: 'Clothing',
    description: 'Iconic nylon puffer with down fill and三角 logo.',
    originalPrice: 2490,
    ourPrice: 1749,
    discount: 30,
    images: ['https://picsum.photos/seed/prada-cloth-1/800/1000'],
    sizes: ['S', 'M', 'L', 'XL'],
    retailerSource: 'Nordstrom',
    retailerUrl: 'https://nordstrom.com/prada-puffer',
    inStock: true,
    sku: 'PRADA-CLOTH-001',
  },
  {
    name: 'Oversized Wool Blazer',
    brand: 'Saint Laurent',
    category: 'Clothing',
    description: 'Double-breasted wool blazer with satin lapels.',
    originalPrice: 3290,
    ourPrice: 2299,
    discount: 30,
    images: ['https://picsum.photos/seed/ysl-cloth-1/800/1000'],
    sizes: ['36', '38', '40', '42', '44'],
    retailerSource: 'Neiman Marcus',
    retailerUrl: 'https://neimanmarcus.com/ysl-blazer',
    inStock: true,
    sku: 'YSL-CLOTH-001',
  },
  {
    name: 'Double Breasted Coat',
    brand: 'Balenciaga',
    category: 'Clothing',
    description: 'Oversized double breasted wool coat.',
    originalPrice: 4590,
    ourPrice: 3199,
    discount: 30,
    images: ['https://picsum.photos/seed/balenciaga-cloth-1/800/1000'],
    sizes: ['S', 'M', 'L'],
    retailerSource: 'Saks',
    retailerUrl: 'https://saks.com/balenciaga-coat',
    inStock: true,
    sku: 'BALENCIAGA-CLOTH-001',
  },
  {
    name: 'Cashmere Turtleneck',
    brand: 'Loro Piana',
    category: 'Clothing',
    description: 'Pure cashmere turtleneck sweater.',
    originalPrice: 1890,
    ourPrice: 1299,
    discount: 31,
    images: ['https://picsum.photos/seed/lp-cloth-1/800/1000'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    retailerSource: 'Neiman Marcus',
    retailerUrl: 'https://neimanmarcus.com/lp-turtleneck',
    inStock: true,
    sku: 'LP-CLOTH-001',
  },
  {
    name: 'Silk Midi Dress',
    brand: 'Celine',
    category: 'Clothing',
    description: 'Elegant silk dress with bow detail.',
    originalPrice: 3690,
    ourPrice: 2599,
    discount: 30,
    images: ['https://picsum.photos/seed/celine-cloth-1/800/1000'],
    sizes: ['XS', 'S', 'M', 'L'],
    retailerSource: 'Saks',
    retailerUrl: 'https://saks.com/celine-dress',
    inStock: true,
    sku: 'CELINE-CLOTH-001',
  },
  // ACCESSORIES
  {
    name: 'GG Belt',
    brand: 'Gucci',
    category: 'Accessories',
    description: 'Double G leather belt in shiny gold finish.',
    originalPrice: 450,
    ourPrice: 299,
    discount: 33,
    images: ['https://picsum.photos/seed/gucci-acc-1/800/1000'],
    sizes: ['S', 'M', 'L'],
    retailerSource: 'Saks',
    retailerUrl: 'https://saks.com/gucci-belt',
    inStock: true,
    sku: 'GUCCI-ACC-001',
  },
  {
    name: 'Re-Edition 2005 Saffiano Card Holder',
    brand: 'Prada',
    category: 'Accessories',
    description: 'Compact card holder in signature Saffiano leather.',
    originalPrice: 340,
    ourPrice: 229,
    discount: 33,
    images: ['https://picsum.photos/seed/prada-acc-1/800/1000'],
    sizes: ['One Size'],
    retailerSource: 'Nordstrom',
    retailerUrl: 'https://nordstrom.com/prada-cardholder',
    inStock: true,
    sku: 'PRADA-ACC-001',
  },
  {
    name: 'Monogram Belt',
    brand: 'Louis Vuitton',
    category: 'Accessories',
    description: 'Signature monogram canvas belt with LV buckle.',
    originalPrice: 490,
    ourPrice: 349,
    discount: 29,
    images: ['https://picsum.photos/seed/lv-acc-1/800/1000'],
    sizes: ['S', 'M', 'L'],
    retailerSource: 'Neiman Marcus',
    retailerUrl: 'https://neimanmarcus.com/lv-belt',
    inStock: true,
    sku: 'LV-ACC-001',
  },
  {
    name: 'Cashmere Scarf',
    brand: 'Burberry',
    category: 'Accessories',
    description: 'Luxurious cashmere scarf with vintage check.',
    originalPrice: 490,
    ourPrice: 329,
    discount: 33,
    images: ['https://picsum.photos/seed/burberry-acc-1/800/1000'],
    sizes: ['One Size'],
    retailerSource: 'Saks',
    retailerUrl: 'https://saks.com/burberry-scarf',
    inStock: true,
    sku: 'BURBERRY-ACC-001',
  },
  {
    name: 'Sunglasses',
    brand: 'Celine',
    category: 'Accessories',
    description: 'Oversized cat-eye sunglasses in acetate.',
    originalPrice: 395,
    ourPrice: 269,
    discount: 32,
    images: ['https://picsum.photos/seed/celine-acc-1/800/1000'],
    sizes: ['One Size'],
    retailerSource: 'Nordstrom',
    retailerUrl: 'https://nordstrom.com/celine-sunglasses',
    inStock: true,
    sku: 'CELINE-ACC-001',
  },
  {
    name: 'Wallet on Chain',
    brand: 'Chanel',
    category: 'Accessories',
    description: 'Classic quilted lambskin wallet with chain strap.',
    originalPrice: 3850,
    ourPrice: 2699,
    discount: 30,
    images: ['https://picsum.photos/seed/chanel-acc-1/800/1000'],
    sizes: ['One Size'],
    retailerSource: 'Neiman Marcus',
    retailerUrl: 'https://neimanmarcus.com/chanel-woc',
    inStock: true,
    sku: 'CHANEL-ACC-001',
  },
  {
    name: 'Small Leather Goods',
    brand: 'Bottega Veneta',
    category: 'Accessories',
    description: 'Card holder in signature intrecciato leather.',
    originalPrice: 390,
    ourPrice: 269,
    discount: 31,
    images: ['https://picsum.photos/seed/bv-acc-1/800/1000'],
    sizes: ['One Size'],
    retailerSource: 'Saks',
    retailerUrl: 'https://saks.com/bv-slg',
    inStock: true,
    sku: 'BV-ACC-001',
  },
  {
    name: 'Silk Tie',
    brand: 'Brunello Cucinelli',
    category: 'Accessories',
    description: 'Hand-rolled silk tie in classic pattern.',
    originalPrice: 395,
    ourPrice: 279,
    discount: 29,
    images: ['https://picsum.photos/seed/bc-acc-1/800/1000'],
    sizes: ['One Size'],
    retailerSource: 'Neiman Marcus',
    retailerUrl: 'https://neimanmarcus.com/bc-tie',
    inStock: true,
    sku: 'BC-ACC-001',
  },
  {
    name: 'Runaway Sneakers',
    brand: 'Dior',
    category: 'Shoes',
    description: 'B23 high-top sneakers in Oblique canvas.',
    originalPrice: 1100,
    ourPrice: 799,
    discount: 27,
    images: ['https://picsum.photos/seed/dior-shoe-1/800/1000'],
    sizes: ['39', '40', '41', '42', '43', '44'],
    retailerSource: 'Neiman Marcus',
    retailerUrl: 'https://neimanmarcus.com/dior-sneakers',
    inStock: true,
    sku: 'DIOR-SHOE-001',
  },
  {
    name: 'Bobby Bag in Smooth Leather',
    brand: 'Hermès',
    category: 'Bags',
    description: 'Elegant hobo bag in supple calfskin.',
    originalPrice: 5350,
    ourPrice: 3850,
    discount: 28,
    images: ['https://picsum.photos/seed/hermes-bag-1/800/1000'],
    sizes: ['One Size'],
    retailerSource: 'Neiman Marcus',
    retailerUrl: 'https://neimanmarcus.com/hermes-bobby',
    inStock: true,
    sku: 'HERMES-BAG-001',
  },
];

const seedRetailers = [
  {
    name: 'Saks',
    baseUrl: 'https://www.saksfifthavenue.com',
    scraperModule: 'saks',
    hasAffiliate: true,
    affiliateNetwork: 'RewardStyle',
    markup: 5,
  },
  {
    name: 'Nordstrom',
    baseUrl: 'https://shop.nordstrom.com',
    scraperModule: 'nordstrom',
    hasAffiliate: true,
    affiliateNetwork: 'RewardStyle',
    markup: 5,
  },
  {
    name: 'Neiman Marcus',
    baseUrl: 'https://www.neimanmarcus.com',
    scraperModule: 'neiman',
    hasAffiliate: true,
    affiliateNetwork: 'RewardStyle',
    markup: 5,
  },
];

async function seed() {
  try {
    const mongoUri = process.env.MONGODB_URI || 'mongodb://localhost:27017/dirty-apple';
    await mongoose.connect(mongoUri);
    console.log('Connected to MongoDB');

    // Clear existing data
    await Product.deleteMany({});
    await Retailer.deleteMany({});
    console.log('Cleared existing data');

    // Insert products
    await Product.insertMany(seedProducts);
    console.log(`Inserted ${seedProducts.length} products`);

    // Insert retailers
    await Retailer.insertMany(seedRetailers);
    console.log(`Inserted ${seedRetailers.length} retailers`);

    console.log('Seed completed successfully!');
  } catch (error) {
    console.error('Seed error:', error);
  } finally {
    await mongoose.disconnect();
    process.exit(0);
  }
}

seed();
